name: Continuos Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./mvnw test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Lint
        run: ./mvnw verify